LiteSQL: litesql::Database Class Reference
litesql::Database Class Reference
A base class of databases.
#include <database.hpp>
Classes
class SchemaItem
intermediate representation of single entity in relational database, table, index or sequence
Public Member Functions
Database (const std::string &backendType, const std::string &connInfo)
opens connection to backend, throw exception if fails or cannot found a Backend class
Database (const Database &op)
opens new connection to same database
virtual ~Database ()
closes database
void create () const
creates database based on getSchema
void drop () const
converts CREATE-statements (of getSchema) to DROP statements and executes them
bool needsUpgrade () const
returns true if schema of backend database is different from schema returned by getSchema.
void upgrade () const
tries to upgrade database on disk so that schemas would be compatible
Records query (const std::string &query) const
executes SQL query
template<class T >
Cursor< T > cursor (const std::string &query) const
void insert (const std::string &table, const Record &r, const std::vector< std::string > &fields=std::vector< std::string >()) const
executes SQL INSERT statement.
std::string groupInsert (const Record &tables, const Records &fields, const Records &values, const std::string &sequence) const
executes multiple INSERT-statements and assigns same 'row id' for first field of every record
void delete_ (const std::string &table, const Expr &e=Expr()) const
deletes rows from single table, deleted rows are selected by Expr if specified
void begin () const
begins SQL transaction
void commit () const
commits SQL transaction
void rollback () const
cancels active SQL transaction
Public Attributes
bool verbose
verbosity, prints queries to cerr if true
Protected Member Functions
void storeSchemaItem (const SchemaItem &s) const
stores SchemaItem to 'schema' - table (deletes old versions)
virtual std::vector< SchemaItem > getSchema () const
returns database schema.
std::vector< SchemaItem > getCurrentSchema () const
queries 'schema' - table and converts results to SchemaItem-objects
void upgradeTable (const std::string &name, const std::string &oldSchema, const std::string &newSchema) const
adds missing and removes extra fields to/from table (tries to preserve data).
bool addColumn (const std::string &name, const ColumnDefinition &column_def) const
Protected Attributes
std::unique_ptr< Backend > backend
backend implementation
Friends
class Updater
Detailed Description
A base class of databases.
Can be used without inheriting own version of Database using query()-method. See Defining Database
Constructor & Destructor Documentation
Database() [1/2]
litesql::Database::Database (const std::string & backendType, const std::string & connInfo)
opens connection to backend, throw exception if fails or cannot found a Backend class
Parameters
backendType backend type ("postgresql","mysql" or "sqlite3")
connInfo connection params, syntax "param=value param=value ..." valid keys: host,user,password,database and port
Database() [2/2]
Database::Database (const Database & op)
opens new connection to same database
Parameters
op opened Database
Member Function Documentation
delete_()
void Database::delete_ (const std::string & table, const Expr & e = Expr()) const
deletes rows from single table, deleted rows are selected by Expr if specified
Parameters
table target table
e selection expression
References query().
Referenced by storeSchemaItem().
getCurrentSchema()
vector< Database::SchemaItem > Database::getCurrentSchema () const protected
queries 'schema' - table and converts results to SchemaItem-objects
Returns
SchemaItem-objects
References query().
Referenced by needsUpgrade(), and upgrade().
getSchema()
virtual std::vector<SchemaItem> litesql::Database::getSchema () const inline protected virtual
returns database schema.
Returns
SchemaItem-objects
Referenced by create(), drop(), needsUpgrade(), and upgrade().
groupInsert()
string Database::groupInsert (const Record & tables, const Records & fields, const Records & values, const std::string & sequence) const
executes multiple INSERT-statements and assigns same 'row id' for first field of every record
Parameters
tables destination tables for insert operation
fields record of field names per table
values record of values per table
sequence sequence where row id-numbers are pulled
Returns
new row id
References backend, litesql::join(), and verbose.
Referenced by litesql::Persistent::insert().
insert()
void Database::insert (const std::string & table, const Record & r, const std::vector< std::string > & fields = std::vector<std::string>()) const
executes SQL INSERT statement.
Parameters
table destination table
r values
fields field names Values are escaped using escapeSQL - function
References litesql::escapeSQL(), litesql::join(), and query().
Referenced by storeSchemaItem().
query()
Records Database::query (const std::string & query) const
executes SQL query
Parameters
query query std::string
Returns
result set
References backend, and verbose.
Referenced by litesql::DataSource< T >::count(), create(), delete_(), drop(), getCurrentSchema(), insert(), upgrade(), and upgradeTable().
upgradeTable()
void Database::upgradeTable (const std::string & name, const std::string & oldSchema, const std::string & newSchema) const protected
adds missing and removes extra fields to/from table (tries to preserve data).
copies data to a temporary table and then back to upgraded table because all backends do not support ALTER TABLE ADD ... - SQL statements.
Parameters
name table name
oldSchema current schema of table
newSchema upgraded schema of table
References begin(), commit(), litesql::join(), and query().
Referenced by upgrade().
The documentation for this class was generated from the following files:
database.hpp
database.cpp