LiteSQL: datasource.hpp File Reference
datasource.hpp File Reference
selectObjectQuery<T> and DataSource<T>
#include "litesql/database.hpp"
#include "litesql/selectquery.hpp"
Classes
class litesql::DataSource< T >
template class which holds SelectQuery for selecting objects of type T
Functions
SelectQuery litesql::selectObjectQuery (const std::vector< FieldType > &fdatas, const Expr &e=Expr())
returns SelectQuery which selects objects of type T
template<class T >
SelectQuery litesql::selectObjectQuery (const Expr &e=Expr())
returns SelectQuery which selects objects of type T
Detailed Description
selectObjectQuery<T> and DataSource<T>
Function Documentation
selectObjectQuery() [1/2]
template<class T > SelectQuery litesql::selectObjectQuery (const Expr & e = Expr())
returns SelectQuery which selects objects of type T
Parameters
e optional filter expression
References litesql::selectObjectQuery().
selectObjectQuery() [2/2]
SelectQuery litesql::selectObjectQuery (const std::vector< FieldType > & fdatas, const Expr & e = Expr())
returns SelectQuery which selects objects of type T
Parameters
fdatas fields of class T
e optional filter expression
References litesql::selectObjectQuery().
Referenced by litesql::DataSource< T >::DataSource(), and litesql::selectObjectQuery().