#ifndef __LitesqlObjectPanel__
#define __LitesqlObjectPanel__

/**
@file
Subclass of ObjectPanel, which is generated by wxFormBuilder.
*/

#include "ui.h"

namespace xml 
{
  class Object;
}

/** Implementing ObjectPanel */
class LitesqlObjectPanel : public ui::ObjectPanel
{
public:
	/** Constructor */
  LitesqlObjectPanel( wxWindow* parent, xml::Object* pObject );
private:
  xml::Object* m_pObject;
};

#endif // __LitesqlObjectPanel__
