#ifndef __LitesqlFieldPanel__
#define __LitesqlFieldPanel__

/**
@file
Subclass of FieldPanel, which is generated by wxFormBuilder.
*/

#include "ui.h"

namespace xml
{
  class Field;
}
/** Implementing FieldPanel */
class LitesqlFieldPanel : public ui::FieldPanel
{
public:
	/** Constructor */
  LitesqlFieldPanel( wxWindow* parent , xml::Field* pField);
private:
  xml::Field* m_pField;
};

#endif // __LitesqlFieldPanel__
