#ifndef __LitesqlDatabasePanel__
#define __LitesqlDatabasePanel__

/**
@file
Subclass of DatabasePanel, which is generated by wxFormBuilder.
*/

#include "ui.h"
#include "ddx.h"

namespace xml {
  class Database;
};

namespace ui {

  /** Implementing DatabasePanel */
  class LitesqlDatabasePanel : public DatabasePanel, TransferableData
  {
  public:
    /** Constructor */
    LitesqlDatabasePanel( wxWindow* parent, xml::Database* db );

    bool TransferDataToWindow()
    { return TransferData(true); }

    bool TransferDataFromWindow()
    { return TransferData(false); }

  protected:
    bool TransferData(bool toWindow);

  private:
    xml::Database* m_database;
  };

}
#endif // __LitesqlDatabasePanel__
