#ifndef __LitesqlDatabasePanel__
#define __LitesqlDatabasePanel__

/**
@file
Subclass of DatabasePanel, which is generated by wxFormBuilder.
*/

#include "ui.h"

namespace xml {
  class Database;
};
namespace ui {

  /** Implementing DatabasePanel */
  class LitesqlDatabasePanel : public DatabasePanel
  {
  public:
    /** Constructor */
    LitesqlDatabasePanel( wxWindow* parent, xml::Database* db );

    // validate the correctness of input, return true if ok
    bool Validate();

    bool LitesqlDatabasePanel::TransferDataToWindow()
    { return TransferData(true); }

    bool LitesqlDatabasePanel::TransferDataFromWindow()
    { return TransferData(false); }

  protected:
    bool TransferData(bool toWindow);


  private:
    xml::Database* m_database;
  };

}
#endif // __LitesqlDatabasePanel__
