#ifndef __LitesqlFieldPanel__
#define __LitesqlFieldPanel__

/**
@file
Subclass of FieldPanel, which is generated by wxFormBuilder.
*/

#include "ui.h"
#include "ddx.h"
#include "LitesqlDocument.h"

/** Implementing FieldPanel */
class LitesqlFieldPanel : public ui::FieldPanel, TransferableData
{
public:
	/** Constructor */
  LitesqlFieldPanel( wxWindow* parent , uiField* pField);

  bool TransferDataToWindow()
    { return TransferData(true); }

    bool TransferDataFromWindow()
    { return TransferData(false); }

protected:
  bool TransferData(bool toWindow);

private:
  uiField* m_pField;
};

#endif // __LitesqlFieldPanel__
