#ifndef __LitesqlFieldPanel__
#define __LitesqlFieldPanel__

/**
@file
Subclass of FieldPanel, which is generated by wxFormBuilder.
*/

#include "ui.h"
#include "ddx.h"
#include "LitesqlDocument.h"

/** Implementing FieldPanel */
class LitesqlFieldPanel : public ui::FieldPanel, TransferableData
{
public:
	/** Constructor */
  LitesqlFieldPanel( wxWindow* parent , uiField* pField);

  bool TransferDataToWindow()    { return TransferData(true); }
  bool TransferDataFromWindow()  { return TransferData(false); }
  
  uiField* GetField()          { return m_pField; }

protected:
  bool TransferData(bool toWindow);

private:
  LitesqlFieldPanel() : ui::FieldPanel(NULL) {};
  DECLARE_DYNAMIC_CLASS(LitesqlFieldPanel);
  
  uiField* m_pField;
  
};

#endif // __LitesqlFieldPanel__
