#ifndef __LitesqlObjectPanel__
#define __LitesqlObjectPanel__

/**
@file
Subclass of ObjectPanel, which is generated by wxFormBuilder.
*/

#include "ui.h"
#include <vector>

namespace xml 
{
  class Object;
}

/** Implementing ObjectPanel */
class LitesqlObjectPanel : public ui::ObjectPanel
{
public:
	/** Constructor */
  LitesqlObjectPanel( wxWindow* parent, std::vector<xml::Object*> baseClasses,xml::Object* pObject );
  xml::Object* GetObject();

  bool TransferDataToWindow()    { return TransferData(true); }
  bool TransferDataFromWindow()  { return TransferData(false); }
  
protected:
  bool TransferData(bool toWindow);

private:
  LitesqlObjectPanel(): ui::ObjectPanel(NULL) {};

  xml::Object* m_pObject;
  DECLARE_DYNAMIC_CLASS(LitesqlObjectPanel);
};

#endif // __LitesqlObjectPanel__
