#ifndef __LitesqlRelationPanel__
#define __LitesqlRelationPanel__

/**
@file
Subclass of RelationPanel, which is generated by wxFormBuilder.
*/
#include <vector>
#include <wx/valgen.h>

#include "ui.h"

namespace xml 
{
  class Object;
  class Relation;
  class Relate;
}

/**Validator for a wxChoice <-> xml::Field::type */
class RelateTypeValidator : public wxGenericValidator {

  DECLARE_DYNAMIC_CLASS(RelateTypeValidator)

public:
  
  RelateTypeValidator (xml::Relate *val = 0);
  RelateTypeValidator (const RelateTypeValidator& val);

  virtual wxObject *Clone() const;
    
  // Called to transfer data to the window
  virtual bool TransferToWindow();

    // Called to transfer data from the window
  virtual bool TransferFromWindow();

private:
  xml::Relate *m_pRelate;
  wxString value; 
};

/** Implementing RelationPanel */
class LitesqlRelationPanel : public ui::RelationPanel
{
public:
  /** Constructor */
  LitesqlRelationPanel( wxWindow* parent , xml::Relation* pRelation);
  void setBaseClasses(const std::vector<xml::Object*>& baseClasses);

private:
  xml::Relation* m_pRelation;
};

#endif // __LitesqlRelationPanel__
