#ifndef MAINFRAME_H
#define MAINFRAME_H

/**
@file
Subclass of DocumentFrameBase, which is generated by wxFormBuilder.
*/

#include "ui.h"
#include <wx/docmdi.h>

class MainFrame: public wxDocMDIParentFrame
{
  DECLARE_CLASS(MainFrame)
 public:
  wxMenu *editMenu;
  
  MainFrame(wxDocManager *manager, wxFrame *frame, const wxString& title, const wxPoint& pos, const wxSize& size,
    long type);
  virtual ~MainFrame();

  void OnAbout(wxCommandEvent& event);
//  MyCanvas *CreateCanvas(wxView *view, wxMDIChildFrame *parent);

DECLARE_EVENT_TABLE()
};



/** Implementing DocumentFrameBase */
class DocumentFrame : public ui::DocumentFrameBase
{
public:
	/** Constructor */
	DocumentFrame( wxWindow* parent );
};

#endif // #ifndef MAINFRAME_H
